[package]
name = "conman"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = { version = "0.26.2", features = ["all-widgets"] }
docker-api = "0.14.0"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-macros = "2.2.0"
